[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://phpc.social/.well-known/webfinger?resource=acct:DrDinoMight@phpc.social"
  status = 200
